Enable OSX as supported system
ArdanaLabs/danalib pull request #7
Opened 2022-03-07 12:54 UTC by EncodePanda

Please note that the *first* commit is formatting the flake using `nixpkgs-fmt`. If you don't agree with this format, please let me know, I will revert that change and apply it to the format that was already here. I don't see we use any formatter for nix files and I thought it might be a first good step. But as mentioned, this is a separate commit.

In this PR we've added dependency on flake-utils which provides:
* `defaultSystems` list which holds both Linux and OSX on aarch64 and x86_64
* `eachSystemMap` which does the same thing as `genAttrs` but a bit differently
  Which is better is debatable, both are good IMHO. Nix folks on the webs are
  using `flake-utils` functions, so I've chosen to follow the herd.

2022-03-07 12:55 UTC, EncodePanda commented
I've confirmed locally that this change works on the Orbis/whitepaper document.

2022-03-07 13:07 UTC, MatthewCroughan requested changes
I'm not in favor of using flake-utils. Let's keep our dependencies minimal and not do that. Otherwise, looks fine, though I'd beware of Nix reducing the macOS support tier, depending on whether there's enough people to maintain it. Supporting macOS is a burden, and it does take engineering resources, Nix does not make it that much easier.

2022-03-07 13:09 UTC, EncodePanda commented
I'm ok with reverting the `flake-utils`. 
Orbis/whitepaper depends on this project. I'm on Mac. I can not build Orbis/whitepaper :)

2022-03-07 13:12 UTC, MatthewCroughan commented
@EncodePanda You can  `docker run -it docker/nix sh` which will get you into a Linux shell with Nix, on macOS if you want. Docker works on macOS, right? :smile: 

Just kidding.

I'm fine with just adding `x86_64-darwin` and `aarch64-darwin` to the supportedSystems, but I'm afraid we aren't going to know whether any of our code works though, I need to hook up CI to this repo. For now, just run `nix flake check`. We may find that one of the Haskell packages we're using doesn't work for aarch64-darwin/x86_64-darwin for example.

2022-03-07 13:15 UTC, EncodePanda commented
I've removed dependency on flake-utils.

I understand the CI burden. We either spin some hydra or make Linux mandatory (is 2022 finally the year of Desktop Linux?)

2022-03-07 13:18 UTC, MatthewCroughan commented
Hmm, since we're not using any part of the flake schema, using attributes like `linters` and `internal`, we've got no way of easily telling whether paths exist in our code. For example, `methane` is not packaged for Darwin. But if you were to reference that path like this
```diff
diff --git a/linters/haskell.nix b/linters/haskell.nix
index 3ec6196..e3ccab4 100644
--- a/linters/haskell.nix
+++ b/linters/haskell.nix
@@ -27,7 +27,7 @@ rec {
     src = src;
     dontBuild = true;
     installPhase = ''
-      PATH="$PATH:${pkgs.git}/bin"
+      PATH="$PATH:${pkgs.methane}/bin"
       export GIT_AUTHOR_NAME="nobody"
       export EMAIL="no@body.com"
       git init
```
`nix flake check` would **not** warn you that `methane` doesn't exist on `x86_64-darwin`.

```
user: matthew swordfish in danalib on  main [!] 
❯ nix flake check
warning: Git tree '/home/matthew/git/platonic/danalib' is dirty
warning: unknown flake output 'internal'
warning: unknown flake output 'linters'
```

I'll have to think of a way to have this checked. For now though, I believe our dependencies are all supported for Darwin, so we might as well merge it.

> We either spin some hydra or make Linux mandatory

Hercules is simpler and will do everything we need, so that's what I'm going to implement. The CI isn't a burden, macOS is a burden though :smile:

2022-03-07 13:45 UTC, MatthewCroughan commented
Hold fire on this, I'm investigating the CI. It wouldn't be good to merge this without CI, because then all we'd do is have a "works on my machine" situation, where we haven't actually tested that any of the code works, but assume it works everywhere just because it works on Linux or macOS, vice versa. 

If it turns out we need to run a macOS agent in order to do decent CI, I have to say I like the idea of making Linux mandatory, rather than going down that rabbit hole. Unless anybody knows how to deploy macOS systems statelessly using Nix. (Which I could be persuaded into implementing).

2022-03-07 17:25 UTC, nixinator commented
We won't be running mac OSX agents. I'd be very interesting to see how mac OSX works, however, if things are working on nix/OS and not on OSX, then we can't deal with that as a priority blocker. 

However, will we attempt to make you successful with the development operating system choice you make. However, this will be to a point, so be perpared to switch when the time comes.

What are your blockers for adopting Nix/OS in the long term.

2022-03-08 07:35 UTC, MatthewCroughan commented
In researching, I ended up asking Robert to implement this https://github.com/hercules-ci/flake-compat-ci/pull/5

What it does is allow Herc to evaluate string context and see if it succeeds or not. Previously, if you had `${pkgs.hello}` shoved somewhere inside of a string, in any of your Nix code, this would go without evaluation by Hercules-Ci, and any errors would not be caught. This meant that the `apps` attribute was effectively not being evaluated deeply enough. But with this fix, we now have a decent evaluation CI for danalib in my branch `mc/herc_ci`.

We can't evaluate for macOS on a regular x86_64-linux machine though, so I'm still going to have to suggest that we don't do this, as we'd have to run a macOS agent, which means interacting with, deploying and managing macOS machines, which is not something I think is very rewarding, or worth the time/effort of the team. Though this may change in future. So we can always re-open this PR in the future and continue when we think it's worth it.

2022-03-08 07:35 UTC, closed without merging

2022-03-08 07:49 UTC, EncodePanda commented
👍